[versions]
agp = "8.5.1"
tools = "31.5.1"
kotlin = "2.0.0"
core-ktx = "1.13.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.2.1"
androidx-hilt-navigation-compose = "1.2.0"
androidx-core-testing = "2.2.0"
androidx-lifecycle = "2.8.3"
espresso-core = "3.6.1"
espresso-device = "1.0.1"
lifecycle-runtime-ktx = "2.8.3"
activity-compose = "1.9.0"
#compose-bom = "2024.04.01"
ksp = "2.0.0-1.0.23"
hilt = "2.51.1"
truth = "1.4.4"
turbine = "1.1.0"
mockk = "1.13.12"
coroutines = "1.8.1"
coil = "2.7.0"
ktor = "2.3.12"
log4j = "1.7.36"
secrets = "2.0.1"
material3 = "1.2.1"
paging3 = "3.3.0"
tracing = "1.2.0"
androidx-compose = "1.7.0-beta05"
navigation-compose = "2.8.0-beta06"
jacoco = "0.8.12"
kotlinx-serialization = "1.7.1"
desugar = "2.0.4"
paparazzi = "1.3.5-SNAPSHOT"
test-parameter-injector = "1.16"
robolectric = "4.13"


[libraries]
## AndroidX
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
#compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidx-compose" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "androidx-compose" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-paging3 = { group = "androidx.paging", name = "paging-compose", version.ref = "paging3" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "androidx-compose" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidx-compose" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "androidx-compose" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidx-compose" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidx-compose" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
tracing = { group = "androidx.tracing", name = "tracing", version.ref = "tracing" }

kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }

## Image loader
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }

## Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }

## Network
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-serialization-kotlinx = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
log4j-android = { group = "org.slf4j", name = "slf4j-android", version.ref = "log4j" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }

## Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-core-arch = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidx-core-testing" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
espresso-device = { group = "androidx.test.espresso", name = "espresso-device", version.ref = "espresso-device" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
paging-test = { group = "androidx.paging", name = "paging-testing", version.ref = "paging3" }
google-testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "test-parameter-injector" }
coil-test = { group = "io.coil-kt", name = "coil-test", version.ref = "coil" }
paparazzi = { group = "app.cash.paparazzi", name = "paparazzi", version.ref = "paparazzi" }
navigation-test = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigation-compose" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "tools" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
gradle-kotlin-compose-compiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

[bundles]
test-commons = [
    "junit",
    "truth",
    "turbine",
    "mockk",
    "coroutines-test",
    "google-testParameterInjector",
    "navigation-test",
    "robolectric"
]
android-test-commons = [
    "mockk-android",
    "androidx-test-ext-junit",
    "espresso-core",
    "espresso-device",
    "ui-test-manifest",
    "ui-test-junit4",
    "hilt-android-testing"
]
ktor = [
    "ktor-client-cio",
    "ktor-content-negotiation",
    "ktor-client-logging",
    "log4j-android"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }

cattose-hilt = { id = "cattose.android.hilt", version = "unspecified" }
cattose-android-application = { id = "cattose.android.application", version = "unspecified" }
cattose-android-application-jacoco = { id = "cattose.android.application.jacoco", version = "unspecified" }
cattose-android-library = { id = "cattose.android.library", version = "unspecified" }
cattose-application-compose = { id = "cattose.android.application.compose", version = "unspecified" }
cattose-library-compose = { id = "cattose.android.library.compose", version = "unspecified" }
cattose-library-jacoco = { id = "cattose.android.library.jacoco", version = "unspecified" }
cattose-feature = { id = "cattose.android.feature", version = "unspecified" }

